AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Approve CodePipeline Approve Action with Slack

Parameters:
  SlackUri:
    Type: String
  PipelineName:
    Type: String

Metadata:
  AWS::ServerlessRepo::Application:
    Name: CodePipelineSlackApproval
    Description: Approve CodePipeline Approve Action with Slack
    Author: ykarakita
    HomePageUrl: https://github.com/ykarakita/code-pipeline-slack-approval
    SourceCodeUrl: https://github.com/ykarakita/code-pipeline-slack-approval
    ReadmeUrl: README.md
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels:
      - CodePipeline
      - Slack
    SemanticVersion: 0.0.8

Resources:
  NotifyApprovalAction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/notify_approval_action.handler
      Runtime: ruby2.5
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          SLACK_URI: !Ref SlackUri
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref Topic
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:GetPipelineState
                - codepipeline:GetPipelineExecution
              Resource:
                - !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}"
  ApprovalCallback:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/approval_callback.handler
      Runtime: ruby2.5
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Events:
        Api:
          Type: Api
          Properties:
            Path: /approve
            Method: post
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - codepipeline:PutApprovalResult
              Resource:
                - !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}/*"
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'CodePipelineApproveAction'
