version: 2.1
jobs:
  package-and-publish:
    docker:
      - image: lambci/lambda:build-python3.7
    steps:
      - checkout
      - run: mkdir target
      - run: zip -r target/app app LICENSE README.md
      - run:
          name: Package SAM Application
          command: sam package --region us-east-1 --template-file template.yaml --output-template-file target/packaged.yaml --s3-bucket sam-artifacts-524176662322-us-east-1
      - run:
          name: Publish SAM Application
          command: sam publish --region us-east-1 --template target/packaged.yaml --semantic-version ${CIRCLE_TAG}

workflows:
  version: 2
  package-and-publish:
    jobs:
      - package-and-publish:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
